/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2010 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package com.mobidonia.tistartapp;

import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;

import org.appcelerator.titanium.TiApplication;
import org.appcelerator.kroll.common.Log;
import org.appcelerator.kroll.common.TiConfig;

import com.startapp.android.publish.ads.nativead.NativeAdDetails;
import com.startapp.android.publish.ads.nativead.NativeAdPreferences;
import com.startapp.android.publish.ads.nativead.StartAppNativeAd;
import com.startapp.android.publish.adsCommon.Ad;
import com.startapp.android.publish.adsCommon.StartAppAd;
import com.startapp.android.publish.adsCommon.StartAppAd.AdMode;
import com.startapp.android.publish.adsCommon.StartAppSDK;
import com.startapp.android.publish.adsCommon.VideoListener;
import com.startapp.android.publish.adsCommon.adListeners.AdDisplayListener;
import com.startapp.android.publish.adsCommon.adListeners.AdEventListener;

import android.app.Activity;


@Kroll.module(name="Tistartapp", id="com.mobidonia.tistartapp")
public class TistartappModule extends KrollModule
{

	// Standard Debugging variables
	private static final String LCAT = "TistartappModule";
	private static final boolean DBG = TiConfig.LOGD;
	private StartAppAd startAppAd;

	// You can define constants with @Kroll.constant, for example:
	// @Kroll.constant public static final String EXTERNAL_NAME = value;

	public TistartappModule()
	{
		super();
	}

	@Kroll.onAppCreate
	public static void onAppCreate(TiApplication app)
	{
		Log.d(LCAT, "inside onAppCreate");
		// put module init code that needs to run when the application is created
		
	
		
	}
	
	// Methods
	@Kroll.method
	public void init(String appId, String developerId) {
		Log.d(LCAT, "init called");
		Activity activity = TiApplication.getAppCurrentActivity();
		StartAppSDK.init(activity, appId, true);
		startAppAd = new StartAppAd(activity);
	}
		

	// Methods
	@Kroll.method
	public String example()
	{
		Log.d(LCAT, "example called");
		return "hello world";
	}

	// Properties
	@Kroll.getProperty
	public String getExampleProp()
	{
		Log.d(LCAT, "get example property");
		return "hello world";
	}


	@Kroll.setProperty
	public void setExampleProp(String value) {
		Log.d(LCAT, "set example property: " + value);
	}
	
	@Kroll.method
	public void showSplash(){
		//Do nothing, since init will show the splash
	}
	
	@Kroll.method
	public void showStandardInterestial(){
		StartAppAd.showAd(TiApplication.getAppCurrentActivity());
	}
	
	
	
	@Kroll.method
	public void onBackPressed() {
		StartAppAd.onBackPressed(TiApplication.getAppCurrentActivity());
		TiApplication.getAppCurrentActivity().onBackPressed();
	}

}

